name: Generate Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # Specify the desired PHP version
          extensions: intl  # Install any necessary PHP extensions

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

       - name: Generate documentation
        run: vendor/bin/phpdoc -d src -t docs

      - name: Commit and Push Documentation
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add docs
          git commit -m "Update documentation"
          git push origin main
