name: PHPDoc

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Generate documentation
        run: vendor/bin/phpdoc -d src -t docs

      - name: Commit and push documentation
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update documentation
          branch: main